# Generated by Django 4.1.7 on 2023-03-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_alter_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
